/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/advanced': RouteRecordInfo<
      '/advanced',
      '/advanced',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/beginner': RouteRecordInfo<
      '/beginner',
      '/beginner',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/challenges/beginner/[id]': RouteRecordInfo<
      '/challenges/beginner/[id]',
      '/challenges/beginner/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/challenges/beginner/02': RouteRecordInfo<
      '/challenges/beginner/02',
      '/challenges/beginner/02',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/challenges/beginner/03': RouteRecordInfo<
      '/challenges/beginner/03',
      '/challenges/beginner/03',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/intermediate': RouteRecordInfo<
      '/intermediate',
      '/intermediate',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/README': RouteRecordInfo<
      '/README',
      '/README',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/advanced.vue': {
      routes:
        | '/advanced'
      views:
        | never
    }
    'src/pages/beginner.vue': {
      routes:
        | '/beginner'
      views:
        | never
    }
    'src/pages/challenges/beginner/[id].vue': {
      routes:
        | '/challenges/beginner/[id]'
      views:
        | never
    }
    'src/pages/challenges/beginner/02.vue': {
      routes:
        | '/challenges/beginner/02'
      views:
        | never
    }
    'src/pages/challenges/beginner/03.vue': {
      routes:
        | '/challenges/beginner/03'
      views:
        | never
    }
    'src/pages/intermediate.vue': {
      routes:
        | '/intermediate'
      views:
        | never
    }
    'src/pages/README.md': {
      routes:
        | '/README'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
